#!/bin/sh
set -e

mount -t proc  -o nosuid,noexec,nodev proc  /proc 2>/dev/null || true
mount -t sysfs -o nosuid,noexec,nodev sysfs /sys  2>/dev/null || true
mount -o remount,rw /

mkdir -p /run/nitro/notify

nitroctl up mdev
nitroctl up acpid
nitroctl up agetty@tty1
nitroctl up agetty@tty2
nitroctl up agetty@tty3

exit 0