#!/bin/sh
set -e

mount -t proc  -o nosuid,noexec,nodev proc  /proc 2>/dev/null || true
mount -t sysfs -o nosuid,noexec,nodev sysfs /sys  2>/dev/null || true
mount -o remount,rw /

mkdir -p /run/nitro/notify

nitroctl up mdev
nitroctl up loadkmap
nitroctl up hostname
